name: My Fist CICD

on:
    push: 
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4.1.1 
            - name: HashiCorp - Setup Terraform
              uses: hashicorp/setup-terraform@v2.0.3
              with:
                 cli_config_credentials_hostname: ${{secrets.USERNAME}}
                 cli_config_credentials_token: ${{secrets.PASSWORD}}
                  
            
