name: My Fist CICD
#comment
on:
    push: 
        branches: ["main"]

jobs:
    subir_servidor:
        runs-on: ubuntu-latest
        env:
           AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
           AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
           AWS_REGION: us-east-2

        steps: 
            - name: Checkout
              uses: actions/checkout@v4.1.1 
            - name: HashiCorp - Setup Terraform
              uses: hashicorp/setup-terraform@v2.0.3
              with:
                 cli_config_credentials_hostname: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                 cli_config_credentials_token: ${{secrets.AWS_ACCESS_KEY_ID}}

            - name: Terraform Init
              id: init
              run: terraform init -upgrade
  
            - name: Terraform Destroy
              id: destroy
              run: terraform destroy --auto-approve

            - name: Terraform Apply
              id: apply
              run: terraform apply --auto-approve
