name: My Fist CICD

on:
    push: 
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4.1.1 
            - name: Docker Login
              uses: docker/login-action@v3.0.0
              with:
                 username: ${{secrets.USERNAME}}
                 password: ${{secrets.PASSWORD}}
                  
            
