name: My Fist CICD

on:
    push: 
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Healthy Checkup
              uses: APina03/wait_for_response@2.0  
            - name: Docker Login
              uses: docker/login-action@v3.0.0
              with:
                 username: ${{secrets.USERNAME}}
                 password: ${{secrets.PASSWORD}}
                  
            
